OT119 46: Endpoint Detalle Slides
alkemyTech/OT-119-SERVER pull request #23
Opened 2022-01-04 20:47 UTC by JimmyDevCode

2022-01-04 21:27 UTC, mkain0 requested changes
@JimmyDevCode Por favor, revisa mis comentarios. Además, no comprendo por qué hay imágenes incluidas en el PR. Sigue faltando adjuntar una request example en la Postman collection.

2022-01-04 21:27 UTC, mkain0 commented on src/main/java/com/alkemy/ong/controller/SlideController.java
> +  private IGetSlideService getByIdSlideService;
Por qué se esta inyectando dos veces la misma clase? Por favor, reutilizar la ya inyectada.

2022-01-04 21:27 UTC, mkain0 commented on src/main/java/com/alkemy/ong/common/EntityUtils.java
> +    OrganizationResponse organizationResponse = convertTo(slide.getOrganizationId());
Esto no compila, no existe ningún método en esta clase que tenga esta firma.

2022-01-04 21:27 UTC, mkain0 commented on src/main/java/com/alkemy/ong/model/response/SlideResponse.java
> +  private OrganizationResponse organization;
Si no se muestran todos los datos de la organización, esto debería ser simplemente organizationId.

2022-01-04 21:27 UTC, mkain0 commented on src/main/java/com/alkemy/ong/service/abstraction/IGetSlideService.java
> +  SlideResponse getById(Long Id);
TRIVIAL: este método se puede llamar directamente getBy ya que el parámetro indica por qué atributo se esta buscando.

2022-01-05 05:39 UTC, JimmyDevCode commented on src/main/java/com/alkemy/ong/model/response/SlideResponse.java
> +  private OrganizationResponse organization;
Entonces, ¿sólo se debería mostrar el id de la organización? Pensé que me debía listar la información del Slide más la información de la Organizacion.
![slides_ok](https://user-images.githubusercontent.com/80182107/148166084-5e50f084-5fc6-4956-b891-73921191142c.png)

2022-01-05 09:33 UTC, mkain0 commented on src/main/java/com/alkemy/ong/model/response/SlideResponse.java
> +  private OrganizationResponse organization;
Si la modificación que hiciste muestra todos los datos de la organization, esta bien... pero el código que esta en esta branch al momento de abrir el PR, no va a mostrar nada de la organization porque no compila, no existe un método en el transformer que pasando un long devuelva un organizationResponse.

2022-01-05 14:17 UTC, JimmyDevCode commented on src/main/java/com/alkemy/ong/common/EntityUtils.java
> +    OrganizationResponse organizationResponse = convertTo(slide.getOrganizationId());
El "slide.getOrganizationId" hace referencia al nombre del atributo organization dentro de la clase slide. Así estaba creado el nombre y solo lo he usado.
![slides_ok](https://user-images.githubusercontent.com/80182107/148232038-2775771f-65d5-460b-ae1c-049f2b0a0be7.png)
 Esto me mostraba al compirarlo.

2022-01-05 14:32 UTC, mkain0 commented on src/main/java/com/alkemy/ong/common/EntityUtils.java
> +    OrganizationResponse organizationResponse = convertTo(slide.getOrganizationId());
Como mostré ayer en la planning utilizando el find usages de GitHub, no existe referencia valida al convert que se esta llamando en esta línea. Por lo tanto, el código no compila y es imposible que te este mostrando la response de la imagen con el último commit pusheado: 553761185e1e6357aee98c1747f07107e9aba85f. 

Incluso, para mayor prueba, si me descargo el código y lo intento compilar:

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project ong: Compilation failure
[ERROR] /OT-119-SERVER/src/main/java/com/alkemy/ong/common/EntityUtils.java:[119,49] no suitable method found for convertTo(com.alkemy.ong.model.entity.Organization)
[ERROR]     method com.alkemy.ong.common.EntityUtils.convertTo(com.alkemy.ong.model.entity.User) is not applicable
[ERROR]       (argument mismatch; com.alkemy.ong.model.entity.Organization cannot be converted to com.alkemy.ong.model.entity.User)
[ERROR]     method com.alkemy.ong.common.EntityUtils.convertTo(com.alkemy.ong.model.entity.Category) is not applicable
[ERROR]       (argument mismatch; com.alkemy.ong.model.entity.Organization cannot be converted to com.alkemy.ong.model.entity.Category)
[ERROR]     method com.alkemy.ong.common.EntityUtils.convertTo(com.alkemy.ong.model.entity.News) is not applicable
[ERROR]       (argument mismatch; com.alkemy.ong.model.entity.Organization cannot be converted to com.alkemy.ong.model.entity.News)
[ERROR]     method com.alkemy.ong.common.EntityUtils.convertTo(java.util.Collection<com.alkemy.ong.model.entity.Slide>) is not applicable
[ERROR]       (argument mismatch; com.alkemy.ong.model.entity.Organization cannot be converted to java.util.Collection<com.alkemy.ong.model.entity.Slide>)
[ERROR]     method com.alkemy.ong.common.EntityUtils.convertTo(com.alkemy.ong.model.entity.Role) is not applicable
[ERROR]       (argument mismatch; com.alkemy.ong.model.entity.Organization cannot be converted to com.alkemy.ong.model.entity.Role)
[ERROR]     method com.alkemy.ong.common.EntityUtils.convertTo(java.util.List<com.alkemy.ong.model.entity.Role>) is not applicable
[ERROR]       (argument mismatch; com.alkemy.ong.model.entity.Organization cannot be converted to java.util.List<com.alkemy.ong.model.entity.Role>)
[ERROR]     method com.alkemy.ong.common.EntityUtils.convertTo(com.alkemy.ong.model.entity.Activity) is not applicable
[ERROR]       (argument mismatch; com.alkemy.ong.model.entity.Organization cannot be converted to com.alkemy.ong.model.entity.Activity)
[ERROR]     method com.alkemy.ong.common.EntityUtils.convertTo(com.alkemy.ong.model.entity.Comment) is not applicable
[ERROR]       (argument mismatch; com.alkemy.ong.model.entity.Organization cannot be converted to com.alkemy.ong.model.entity.Comment)

```

2022-01-06 07:11 UTC, JimmyDevCode reviewed
Tuve algunos inconvenientes porque mi rama no estaba actualizada con la principal. Hice el git pull y me actualizó, pero aun así me tiraba errores para hacer el push. Ahora veo que se han subido los cambios que actualicé en mi rama y además los que fusione de la principal. No sé si está correcto @mkain0

2022-01-06 12:14 UTC, mkain0 approved these changes

2022-01-06 12:14 UTC, merged