Ot119-47: Implemented endpoint to create slides according to the ticket requirements
alkemyTech/OT-119-SERVER pull request #29
Opened 2022-01-07 21:35 UTC by asanmartinezp

Implemented the slide creation with the requested validations.

Evidence:
![Evidence](https://user-images.githubusercontent.com/94468975/148610382-9c815755-6228-4b7b-a2ae-44bdb67c8571.png)

2022-01-09 12:57 UTC, mkain0 requested changes
@asanmartinezp Fijate que hay unos conflictos en el PR posiblemente producto de un merge de otro PR que hice anteriormente a revisar el tuyo.

2022-01-09 12:57 UTC, mkain0 commented on src/main/java/com/alkemy/ong/repository/ISlideRepository.java
> +  @Query(value = "SELECT MAX(slide_order) FROM slides", nativeQuery = true)
Modificar esto para que utilice JPQL. Utilizar nativeQuery es una mala práctica.

2022-01-09 12:57 UTC, mkain0 commented on src/main/java/com/alkemy/ong/repository/ISlideRepository.java
> +  Integer getMaxtSlideOrder();
Este método puede devolver un primitivo directamente para evitar realizar todas las validaciones de la línea 74 en el servicio.

2022-01-09 12:57 UTC, mkain0 commented on src/main/java/com/alkemy/ong/model/request/SlideRequest.java
> +  @NotBlank
Falta el error message en caso de que sea blank.

2022-01-09 12:57 UTC, mkain0 commented on src/main/java/com/alkemy/ong/model/request/SlideRequest.java
> +  @NotBlank
Falta el error message en caso de que sea blank.

2022-01-09 12:57 UTC, mkain0 commented on src/main/java/com/alkemy/ong/service/SlideServiceImpl.java
> +  ImageUtils imageUtils;
TRIVIAL: private access modifier.

2022-01-09 12:57 UTC, mkain0 commented on src/main/java/com/alkemy/ong/service/SlideServiceImpl.java
> +  IGetOrganizationService getOrganizationService;
TRIVIAL: private access modifier.

2022-01-09 12:57 UTC, mkain0 commented on src/main/java/com/alkemy/ong/service/SlideServiceImpl.java
> +  private InputStream convertToInputStream(String encodedString) {
MINOR: convertTo(endcodedString) es suficiente para el nombre de este método ya que el tipo de retorno te indica en que se esta convirtiendo.

2022-01-09 12:57 UTC, mkain0 commented on src/main/java/com/alkemy/ong/service/SlideServiceImpl.java
> +      slideRequest.setOrder(maxOrder + 1);
La llamada al repositorio de la línea  73, la realizaría solo si el order de la request es null o cero, dependiendo de si es primitivo o no primitivo el atributo de la request. Sino, se estaría llamando siempre a la base de datos con un getMaxSlideOrder incluso cuando le este pasando un valor en la request.

2022-01-09 12:57 UTC, mkain0 commented on src/main/java/com/alkemy/ong/service/SlideServiceImpl.java
> +    String fileName = (slideRequest.getFileName() == null || slideRequest.getFileName().isEmpty())
StringUtils.hasText(slideRequest.getFileName) para no reinventar la rueda.

2022-01-09 12:57 UTC, mkain0 commented on src/main/java/com/alkemy/ong/service/SlideServiceImpl.java
> +        ? UUID.randomUUID().toString() : slideRequest.getFileName();
Estas líneas se podrían extraer a un método privado getFileNameOrDefault(slideRequest.getFileName)

2022-01-09 12:57 UTC, mkain0 commented on src/main/java/com/alkemy/ong/service/SlideServiceImpl.java
> +    }
Estas líneas se podrían extraer a un método privado getSlideOrder() y solo debería ser llamado si el request.getSlideOrder es null o cero dependiendo.

2022-01-09 12:57 UTC, mkain0 commented on src/main/java/com/alkemy/ong/service/SlideServiceImpl.java
> +    slide.setOrganization(organization);
Esta lógica se podría extraer a un método privado buildSlide(imageUrl, slideRequest.getText(), slideRequest.getOrder()).

2022-01-09 13:16 UTC, asanmartinezp commented on src/main/java/com/alkemy/ong/repository/ISlideRepository.java
> +  Integer getMaxtSlideOrder();
Inicialmente lo hice así, pero al probar cuando la table de slides estaba vacía tenía problemas, por eso estaba usando un Integer y hago todas esas validaciones

2022-01-09 13:28 UTC, mkain0 commented on src/main/java/com/alkemy/ong/repository/ISlideRepository.java
> +  Integer getMaxtSlideOrder();
Podes utilizar coalesce en combinación con max. Si no hay nada, te devuelve 0.

2022-01-10 09:26 UTC, mkain0 commented on src/main/java/com/alkemy/ong/repository/ISlideRepository.java
> +  int getMaxtSlideOrder();
Typo: sobra una t.

2022-01-10 09:27 UTC, mkain0 approved these changes

2022-01-10 09:27 UTC, merged