OT119-65: Agregar paginación a Categorías
alkemyTech/OT-119-SERVER pull request #30
Opened 2022-01-08 22:20 UTC by anyuferrari

### Evidence

- Body
![imagen](https://user-images.githubusercontent.com/20570379/148661790-0406cfd7-707b-4664-ae3e-0c02bc0c2404.png)
-Links on header:
![imagen](https://user-images.githubusercontent.com/20570379/148661835-4237960e-7a7c-4508-a1d1-9cbec286ad67.png)

2022-01-09 13:13 UTC, mkain0 requested changes
@anyuferrari Posiblemente tengas que arreglar conflictos antes de solicitar nuevamente una revisión ya que se mergo un PR en main hace unos minutos.

2022-01-09 13:13 UTC, mkain0 commented on src/main/java/com/alkemy/ong/controller/CategoryController.java
> +  }
Este código esta generando un nuevo endpoint. El ticket no crea un nuevo endpoint, extiende el ya existente, es decir, el definido en la linea 60. Estos cambios deben ser incorporados a la linea 60.

2022-01-09 13:13 UTC, mkain0 commented on src/main/java/com/alkemy/ong/repository/ICategoryRepository.java
> +  Page<Category> findAll(Pageable pageable);
Este método esta trayendo también las categorías eliminadas. Por lo tanto, la forma correcta sería:

`Page<Category> findBySoftDeleteFalse(Pageable pageable);`

2022-01-09 13:13 UTC, mkain0 commented on src/main/java/com/alkemy/ong/repository/ICategoryRepository.java
> +    PagingAndSortingRepository<Category, Long> {
Ninguna clase de Java puede extender de más de una clase. Pues, la multi herencia no existe en Java y solo es posible simularla utilizando interfaces. Entonces te preguntarás cómo compiló el código? Básicamente porque JpaRepository extiende de PagingAndSortingRepository. Sin embargo, es redundante, y no es necesario. Por favor, remover el código aplicado.

2022-01-09 13:13 UTC, mkain0 commented on src/main/java/com/alkemy/ong/repository/ICategoryRepository.java
> +  @Override
No creo que el Override sea necesario.

2022-01-09 13:13 UTC, mkain0 commented on src/main/java/com/alkemy/ong/service/CategoryServiceImpl.java
> +  }
Este método no debe existir, los cambios deben ser aplicados sobre el list, ya que el ticket es una extensión del servicio existente.

2022-01-09 13:13 UTC, mkain0 commented on src/main/java/com/alkemy/ong/service/abstraction/IGetCategoryService.java
> +  Page<Category> findPaginated(Pageable pageable);
Este método no debe existir, los cambios deben ser aplicados sobre el list, ya que el ticket es una extensión del servicio existente. Es decir, el método definido en la linea 15.

2022-01-09 13:13 UTC, mkain0 commented on src/main/java/com/alkemy/ong/service/abstraction/IGetCategoryService.java
> +      HttpServletResponse response);
Los parámetros y el no retorno de data de este método son una señal de que este comportamiento es genérico. Qué quiero decir con esto? que si el response tuviera una lista de Testimonials, Users... o X y yo quisiera agregarle paginación al listado y agregar estas headers en la response, podría llamar a este método sin problema. Es decir, no es propio de Category. Por lo tanto, tendría que estar definido en otra interfaz: `IAddPaginationHeaders` y en ese contexto podríamos renombrar el método a `add(UriComponentsBuilder uriBuilder, int page, int totalPages, int pageSize, HttpServletResponse response);` ya que el nombre de la interfaz nos sirve de más detalles sobre su uso.

2022-01-09 13:13 UTC, mkain0 commented on src/main/java/com/alkemy/ong/service/CategoryServiceImpl.java
> +    uriBuilder.path("/categories");
El path lo podes incorporar como un parámetro del método para hacerlo más genérico.

2022-01-09 15:30 UTC, anyuferrari commented on src/main/java/com/alkemy/ong/controller/CategoryController.java
> +  }
Hay algo que no entiendo sobre esto... el método puede devolver o bien un responseEntity con la lista de categorías, o una paginación... si modifico para que devuelva la paginación no estaría deshaciendo lo que hice en el ticket que pedía que devuelva una lista de categorías?

2022-01-09 16:37 UTC, mkain0 commented on src/main/java/com/alkemy/ong/controller/CategoryController.java
> +  }
No, porque el endpoint sigue devolviendo una lista, pero ahora la devuelve paginada.

2022-01-10 13:35 UTC, mkain0 commented on src/main/java/com/alkemy/ong/controller/CategoryController.java
> +  public ResponseEntity<Page<Category>> list(@RequestParam(value = "page", required = false) int page,
MINOR: page tiene que ser requerido.

2022-01-10 13:36 UTC, mkain0 approved these changes

2022-01-10 13:36 UTC, merged