OT119-77: Created a test for the HTTP GET method at the endpoint /organization/public.
alkemyTech/OT-119-SERVER pull request #34
Opened 2022-01-11 12:22 UTC by asanmartinezp

No estoy seguro si la implementación del test es la correcta por el uso de la anotación @WebMvcTest y el uso del objeto MockMvc, ya que estos no son usados en los tests de ejemplo.

2022-01-11 12:57 UTC, mkain0 commented
@asanmartinezp dado que el proyecto no esta utilizando MockMvc, no deberías estar utilizando esa clase. Por favor, realiza los test con las clases utilizadas en los ejemplos provistos en el repositorio.

2022-01-11 16:02 UTC, asanmartinezp commented
Ahora lo implementé con las mismas clases de los ejemplos, sin embargo no estoy seguro de si el test está correctamente hecho porque lo único que hace es verificar que el endpoint exista básicamente. ¿Debería verificar los datos de la organización? No lo hice así porque seguramente todos tenemos datos diferentes para las pruebas.

2022-01-11 17:01 UTC, mkain0 requested changes

2022-01-11 17:01 UTC, mkain0 commented on src/test/java/com/alkemy/ong/integration/organization/OrganizationPublicEndpointIntegrationTest.java
> +  OrganizationServiceImpl organizationService;
Si mockeas el organizationService, esto ya no sería un integration test, sino que sería un unit test. Básicamente lo que hace este código es cuando llama a organizationService.getOrganizationWithSlides() returna null y como eso no es un problema para el controller, el controller devuelve OK y tenemos un green test. Sin embargo, no esta testeando nada ni verificando nada que sea util en caso de que se hagan modificaciones al código en una posterior iteración.

Si esto fuera un unit test de la clase controller, mockearia el servicio, ya que lo único que me importa en el contexto del controller es que devuelva un 200 y que se llame al organizationService. FOR YOUR INFORMATION: Para verificar que efectivamente haya iteración con el service puedo usar el metodo verify de Mockito.

Pero esto no es un unit test, es un test de integración... Por lo tanto, el código debe pasar por el service real, no debo mockearlo. Lo único mockeado en este test deberían ser los repositorios. Al mockear los repositorios, vas a tener acceso a poder verificar la response del servicio con algo como:

```
    OrganizationResponse responseBody = response.getBody();
    assertNotNull(responseBody);
    assertEquals(responseBody.getEmail(), "whatever is set in the stub class");
    assertEquals(responseBody.getImage(), "whatever is set in the stub class");
```

2022-01-11 17:05 UTC, mkain0 commented on src/test/java/com/alkemy/ong/integration/organization/OrganizationPublicEndpointIntegrationTest.java
> +  OrganizationServiceImpl organizationService;
Adicionalmente, los test de integración en un proyecto real no suelen contener mocks. Salvo que sean isolation test. Para minimizar el scope de la tarea estamos utilizando mocks en los repositorios para los test de integración y de paso les permite a ustedes comprender el uso de un mock. Ya que los mismo son la base para los unit test.

2022-01-12 09:25 UTC, mkain0 approved these changes

2022-01-12 09:25 UTC, mkain0 commented on src/test/java/com/alkemy/ong/integration/organization/OrganizationPublicEndpointIntegrationTest.java
> +  private final String PATH = "/organization/public";
Debería ser una constante.

2022-01-12 09:25 UTC, mkain0 commented on src/test/java/com/alkemy/ong/integration/organization/OrganizationPublicEndpointIntegrationTest.java
> +  private List<Slide> slidesStub = new ArrayList<>();
Si algo en el test es un atributo de la clase que no es un mock, es conveniente que sea final.

2022-01-12 09:25 UTC, mkain0 commented on src/test/java/com/alkemy/ong/integration/organization/OrganizationPublicEndpointIntegrationTest.java
> +  private ArrayList<Organization> organizationsStub = new ArrayList<>();
En la definición de la variable siempre se busca lo genérico, mientras que cuando se crea la instancia se especifica la clase que se esta utilizando.

2022-01-12 09:25 UTC, mkain0 commented on src/test/java/com/alkemy/ong/integration/organization/OrganizationPublicEndpointIntegrationTest.java
> +    slide2.setOrder(2);
Esto es código duplicado, debería ser extraído a un método.

2022-01-12 09:25 UTC, mkain0 commented on src/test/java/com/alkemy/ong/integration/organization/OrganizationPublicEndpointIntegrationTest.java
> +    LinkedHashMap responseBody = (LinkedHashMap) response.getBody();
El body debería ser del tipo que este definido en la response del servicio y de esa forma no tendrías que utilizar los String hardcodeados para saber cada parte del body.

2022-01-12 09:26 UTC, merged