OT119-26-endpoint-para-listar-usuarios
alkemyTech/OT-119-SERVER pull request #7
Opened 2021-12-19 18:42 UTC by MiguezPablo

2021-12-19 21:57 UTC, mkain0 requested changes

2021-12-19 21:57 UTC, mkain0 commented on src/main/java/com/alkemy/ong/common/EntityUtils.java
> +    List<UserResponse> userResponseList = new ArrayList<>();
MINOR: como buena practica, los nombres de las variables no deben dar detalle de su implementación.

2021-12-19 21:57 UTC, mkain0 commented on src/main/java/com/alkemy/ong/common/EntityUtils.java
> +    for (User user:users) {
Este método no esta utilizando el codeStyle definido en el README.md

2021-12-19 21:57 UTC, mkain0 commented on src/main/java/com/alkemy/ong/controller/UserController.java
> +  public ResponseEntity<List<UserResponse>> get() {
list sería un nombre más representativo.

2021-12-19 21:57 UTC, mkain0 commented on src/main/java/com/alkemy/ong/controller/UserController.java
> +    List<UserResponse> userResponseList = getUserService.getListUserResponse();
Mismo comentario sobre el nombre de las variables. El nombre de la variable no debe brindar detalles de su implementación.

2021-12-19 21:57 UTC, mkain0 commented on src/main/java/com/alkemy/ong/controller/UserController.java
> +    return new ResponseEntity<>(userResponseList, HttpStatus.OK);
Esta response no satisface los requerimientos conversados en la planning. El json de la response debería ser:
```

{ 
 "users": [
     {
           "email": "john@gmail.com",
           // other attributes
     },
     {
           "email": "paul@gmail.com",
           // more attributes
     }
 ]
}
```

2021-12-19 21:57 UTC, mkain0 commented on src/main/java/com/alkemy/ong/service/UserServiceImpl.java
> +    List<User> userList = userRepository.findAll();
Mismo comentario respecto a nombre de las variable > users instead of userList

2021-12-19 21:57 UTC, mkain0 commented on src/main/java/com/alkemy/ong/service/abstraction/IGetUserService.java
> +  List<UserResponse> getListUserResponse();
list es más que suficiente para indicar lo que hace el método.

2021-12-19 21:57 UTC, mkain0 commented on src/main/java/com/alkemy/ong/model/response/UserResponse.java
> +  private List<Role> roles;
Role es una entity, las entities no deben ser expuestas por el servicio. Utilizar DTO.

2021-12-19 21:58 UTC, mkain0 commented
```
Notes to myself:

- Title, commits and branch name properly set.
- Ticket in right status when PR was opening.
- Time isn't registered.
- Missing evidence attached to the PR. Missing update in Postman collection.
```

2021-12-19 21:59 UTC, mkain0 commented
@MiguezPablo Falta actualizar la Postman collection con el nuevo endpoint. 
Revisa mis comentarios y hace click en "Re-review request" cuando este listo para revisar nuevamente. Gracias!

2021-12-19 23:02 UTC, MiguezPablo commented on src/main/java/com/alkemy/ong/model/response/UserResponse.java
> +  private List<Role> roles;
Para confirmar, en vez de una lista de roles deberia ser una lista de "rolesDTO" digamos.

2021-12-19 23:35 UTC, MiguezPablo commented on src/main/java/com/alkemy/ong/controller/UserController.java
> +    return new ResponseEntity<>(userResponseList, HttpStatus.OK);
Una consulta yo use la annotation @JsonRootName en userResponse pero no me lo toma. Que otra alternativa puedo usar?

2021-12-19 23:38 UTC, mkain0 commented on src/main/java/com/alkemy/ong/controller/UserController.java
> +    return new ResponseEntity<>(userResponseList, HttpStatus.OK);
No te lo toma porque no esta configurado correctamente. 
Otra alternativa es crear una clase ListUserResponse que tenga un `List<UserResponse> users`. En este caso, deberias remover la annotation @JsonRootName de la clase UserResponse.

2021-12-20 00:15 UTC, MiguezPablo commented on src/main/java/com/alkemy/ong/controller/UserController.java
> +    return new ResponseEntity<>(userResponseList, HttpStatus.OK);
Dale muchas gracias

2021-12-20 16:10 UTC, mkain0 requested changes
@MiguezPablo este branch no compila. Por favor, arreglar los conflictos y solicitar revision nuevamente.

2021-12-20 23:59 UTC, MiguezPablo commented
Considero que esta ready tomerge. Gracias

2021-12-21 09:53 UTC, mkain0 commented on src/main/java/com/alkemy/ong/common/EntityUtils.java
> +   public static ListUserResponse convert2(List<User> users) {
Este no es un nombre representativo para el método.

2021-12-21 09:57 UTC, mkain0 commented on src/main/java/com/alkemy/ong/model/response/ListUserResponse.java
> +@JsonRootName(value = "Users")
Esto lo conversamos en la daily. Si se utiliza esta annotation se debe refactorizar todo el código existente para utilizar, caso contrario, no utilizarla.

2021-12-21 09:57 UTC, mkain0 commented on src/main/java/com/alkemy/ong/model/response/ListUserResponse.java
> +public class ListUserResponse extends ArrayList {
Por qué ListUserResponse necesita extender de ArrayList?

2021-12-21 09:57 UTC, mkain0 commented on src/main/java/com/alkemy/ong/common/EntityUtils.java
> +      userResponses.add(userResponse);
En mi opinión, esto no funciona.

2021-12-21 09:59 UTC, mkain0 commented on src/main/java/com/alkemy/ong/service/UserServiceImpl.java
> +  }*/
BUENAS PRACTICAS: no se debe dejar código comentado.

2021-12-21 10:01 UTC, mkain0 approved these changes
@MiguezPablo Revisa mi último commit para ver como ammendar los últimos comentarios. Cualquier duda, avisame.

2021-12-21 10:01 UTC, merged

2021-12-21 11:26 UTC, MiguezPablo commented on src/main/java/com/alkemy/ong/model/response/ListUserResponse.java
> +public class ListUserResponse extends ArrayList {
Para poder utilizar el método .add de la clase ArrayList

2021-12-21 11:30 UTC, MiguezPablo commented on src/main/java/com/alkemy/ong/model/response/ListUserResponse.java
> +public class ListUserResponse extends ArrayList {
Porque yo usaba el constructor vacío de la clase en el método para convertir veo que lo inicializas como un nuevo ArrayList así que no haría falta en ese caso.

2021-12-21 12:17 UTC, mkain0 commented on src/main/java/com/alkemy/ong/model/response/ListUserResponse.java
> +public class ListUserResponse extends ArrayList {
Pues hay varios errores al extender de ArrayList:

- No esta indicado el type de la lista. Por lo cual se torna inseguro el código en runtime.
- Se esta heredados métodos como el equals que pueden no aplicar para esta clase. Por lo tanto, se deben sobreescribir esos métodos.

Para concluir, el esfuerzo de hacer todo para poder extender correctamente de ArrayList es superior a crear una lista de UserResponse y setearlo al ListUserResponse, ya sea utilizando setter o constructor.

2021-12-21 14:03 UTC, MiguezPablo commented on src/main/java/com/alkemy/ong/model/response/ListUserResponse.java
> +public class ListUserResponse extends ArrayList {
Dale mala mía tenés razón.  Muchas gracias